name: CI

on:
  push:
    branches: [$default-branch]
  pull_request:
  workflow_dispatch:

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      # Checkout the code
      - uses: actions/checkout@v2

      # Setup node environment
      - uses: actions/setup-node@v2
        with:
          node-version: "14"
          cache: "npm"

      # Install and cache dependencies
      - name: "Install"
        run: npm install

      # Build and bundle the react app
      - name: "Build"
        run: CI=false && npm run build

  Lint:
    runs-on: ubuntu-latest
    steps:
      # Checkout the code
      - uses: actions/checkout@v2

      # Setup node environment
      - uses: actions/setup-node@v2
        with:
          node-version: "14"
          cache: "npm"

      # Install and cache dependencies
      - name: "Install"
        run: npm install

      # Run linter
      - name: "Lint"
        run: npm run lint

  Test:
    runs-on: ubuntu-latest
    steps:
      # Checkout the code
      - uses: actions/checkout@v2

      # Setup node environment
      - uses: actions/setup-node@v2
        with:
          node-version: "14"
          cache: "npm"

      # Install and cache dependencies
      - name: "Install"
        run: npm install

      # Run test suite
      - name: "Test"
        run: npm run test
